//  \D QUALQUER DIGITO
//  \W-MINUSCULO ALFANUMERICO ("TESTE")
//  \S QUALUER COM EPAÇO EM BRANCO
//  \D QUE NAO SAO DIGITODS
//  \W-MAIUSCULO CARACTERE NAO-AÇFANUMERICOS
//  \S-MAIUSCULO QUE N SEJA ESPAÇO EM BRANCO
//  . QUALQUER CARACTERE, MENOS NOVA LINHA